### ISSUE TITLE
Echidna Exercise 5 bug not found

### ISSUE THREAD

**Issue by enginer** [crytic/building-secure-contracts#126]
In [Echidna Exercise 5](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/Exercise-5.md) with echidna-test version 2.0.2 no bug found
```
Analyzing contract: /damn-vulnerable-defi/contracts/unstoppable/UnstoppableEchidna.sol:UnstoppableEchidna
echidna_testFlashLoan:  passed! 🎉

Unique instructions: 3001
Unique codehashes: 4
Corpus size: 14
Seed: -5156005997475524194
```
But according to assignment should be something like this
```
echidna_testFlashLoan: failed!💥  
  Call sequence:
    transfer(0x62d69f6867a0a084c6d313943dc22023bc263691,1296000)
```

**Comment by anishnaik** [comment]
Hi @enginer did you make sure to use the [hardhat config file ](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/exercises/exercise5/example.hardhat.config.ts) that was provided in the exercise repo?

**Comment by enginer** [comment]
Thanks @anishnaik , yes I commented out `dependencyCompiler` section in hardhat.config.js, and I use config.yaml with multi-abi: true according to instruction

**Comment by anishnaik** [comment]
Did you comment out the `_transfer` function in `contracts/the-rewarder/AccountingToken.sol` (step 5 in the README)?

The reason why this is important is b/c a token transfer to the pool will cause the test to break. However, due to Solidity inheritance,  a `transfer` call will call the internal `_transfer` function in `AccountingToken`. This `_transfer` function simply reverts. Thus, echidna is not able to find the bug.

Hope this makes sense :)

**Comment by anishnaik** [comment]
@enginer did you try the above?

**Comment by enginer** [comment]
@anishnaik Thank you very much, you was right! It was unclear why we need to comment `_transfer` function. Maybe it is make sense to update description and emphasize what commenting is required.

**Comment by anishnaik** [comment]
That's a good point @enginer, I can go ahead and update the description. Thank you for your feedback.

**Comment by Gmskjunior** [comment]
Exit

Em seg., 22 de ago. de 2022 19:09, Lebid Yuriy ***@***.***>
escreveu:
