### ISSUE TITLE
Render better solidity file

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#247]
Right now, the solidity files are not directly rendered in secure-contracts, and the files are dl. We should investigate how to make this a better experience with mdbook

**Comment by montyly** [comment]
One solution is to change the links to point to the github page.
Ex: 
- https://secure-contracts.com/program-analysis/echidna/example/TestDepositWithPermit.sol
- versus https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/example/TestDepositWithPermit.sol

**Comment by montyly** [comment]
We want to keep the solidity code as separate solidity files, for a couple of reasons:
- It's easier for people to use them
- It's easier when we do a workshop 
- We can run them through a CI

**Comment by 0xPhaze** [comment]
Yes, I would suggest keeping them as separate files, but also including the solutions into the markdown as dropdowns (now the user doesn't have to look around in multiple pages). The problem here though is keeping the embedded code up-to-date. Perhaps we can take a look at: 
- [actions/markdown-embed-code-from-file](https://github.com/marketplace/actions/markdown-embed-code-from-file)

This could be useful in a few other places as well

**Comment by montyly** [comment]
Done with #264
